
#Card properties
STAR_ODDS=4
NUM_PEBBLES_PER_CARD=5
ZERO=0
NUM_COLORS=5

#Equation properties
MAX_NUM_PEBBLES_PER_SIDE=4

#GameBoard properties
NUM_VISIBLE_CARDS = 4
NUM_TOTAL_CARDS = 20

#Bank properties
NUM_STARTING_PEBBLES=20

#Referee properties
MINIMUM_NUM_PLAYERS=2
MAXIMUM_NUM_PLAYERS=6