# Generated by Django 5.1.4 on 2025-04-14 14:31

import abroadhub.models
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='Discover amazing study abroad opportunities and expand your horizons. Join our community of global learners today!')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('department', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Assumption of Risk Form', 'Assumption of Risk Form'), ('Acknowledgement of the Code of Conduct', 'Acknowledgement of the Code of Conduct'), ('Housing Questionnaire', 'Housing Questionnaire'), ('Medical/Health History and Immunization Records', 'Medical/Health History and Immunization Records')], max_length=100, unique=True)),
                ('template_file', models.FileField(upload_to='document_templates/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Your Institution')),
            ],
        ),
        migrations.CreateModel(
            name='LogoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='logo/', validators=[abroadhub.models.validate_image])),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(default='#D3D3D3')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(default='#000000')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('4.0'))])),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Student', 'Student'), ('Administrator', 'Administrator'), ('Reviewer', 'Reviewer'), ('Faculty', 'Faculty'), ('Partner', 'Partner')], max_length=20), default=abroadhub.models.AppUser.get_default_roles, size=None)),
                ('dob', models.DateField(blank=True, null=True, validators=[abroadhub.models.AppUser.validate_dob])),
                ('is_sso', models.BooleanField(default=False)),
                ('use_mfa', models.BooleanField(default=False, verbose_name='Enable MFA')),
                ('ulink_username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='abroadhub.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Eligible', 'Eligible'), ('Approved', 'Approved'), ('Enrolled', 'Enrolled'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Withdrawn', 'Withdrawn')], default='Applied', max_length=50)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('Null', 'Null'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Fully Paid', 'Fully Paid')], default='Null', max_length=50)),
                ('assumption_of_risk_form', models.FileField(blank=True, null=True, upload_to=abroadhub.models.get_upload_path)),
                ('assumption_of_risk_form_timestamp', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_of_code_of_conduct', models.FileField(blank=True, null=True, upload_to=abroadhub.models.get_upload_path)),
                ('acknowledgement_of_code_of_conduct_timestamp', models.DateTimeField(blank=True, null=True)),
                ('housing_questionnaire', models.FileField(blank=True, null=True, upload_to=abroadhub.models.get_upload_path)),
                ('housing_questionnaire_timestamp', models.DateTimeField(blank=True, null=True)),
                ('medical_health_history_and_immunization_records', models.FileField(blank=True, null=True, upload_to=abroadhub.models.get_upload_path)),
                ('medical_health_history_and_immunization_records_timestamp', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='abroadhub.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='ConfidentialNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='abroadhub.application')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abroadhub.appuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], default='Fall', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('open_date', models.DateField()),
                ('deadline', models.DateField()),
                ('essential_doc_deadline', models.DateField()),
                ('payment_deadline', models.DateField(blank=True, null=True)),
                ('track_payment', models.BooleanField(default=False)),
                ('faculty_leads', models.ManyToManyField(related_name='programs_led', to='abroadhub.appuser')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for_programs', to='abroadhub.course')),
                ('provider_partners', models.ManyToManyField(blank=True, related_name='provider_programs', to='abroadhub.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abroadhub.program'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='abroadhub.program')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='abroadhub.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abroadhub.question')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(max_length=100)),
                ('writer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=20)),
                ('token', models.UUIDField(unique=True)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_date', models.DateTimeField(blank=True, null=True)),
                ('letter_file', models.FileField(blank=True, null=True, upload_to='recommendation_letters/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_letters', to='abroadhub.application')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_refreshed', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='abroadhub.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'F'), ('IP', 'In Progress'), ('W', 'Withdrawn')], max_length=3)),
                ('term', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(default=abroadhub.models.get_default_course, on_delete=django.db.models.deletion.CASCADE, related_name='course_records', to='abroadhub.course')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='abroadhub.transcriptcache')),
            ],
        ),
    ]
