"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
MAILCHIMP_API_KEY = os.getenv('MAILCHIMP_API_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['abroad.colab.duke.edu', 'localhost', '127.0.0.1','vcm-45223.vm.duke.edu']

STATIC_URL = '/static/'
STATIC_ROOT = '/home/jc870/abroad-hub/backend/static/'


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "abroadhub.authentication.JWTNetIDAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Equivalent to SESSION_COOKIE_AGE = 15 * 60
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # How long the refresh token is valid
    'ROTATE_REFRESH_TOKENS': True,                   # Similar to SESSION_SAVE_EVERY_REQUEST
    'UPDATE_LAST_LOGIN': True,                       # Tracks login time (optional)
}


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'abroadhub',
    'django_otp',
    'django_otp.plugins.otp_totp',  # TOTP plugin for Google Authenticator
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'audit_logging.audit_middleware.AuditLoggingMiddleware',
    'django_otp.middleware.OTPMiddleware',


]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PWD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOWED_ORIGINS = [
    # "https://abroad.colab.duke.edu", #for production
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:3000",  # Add this
    "http://127.0.0.1:8000"   # Add this
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'x-id-token',
    'accept',
    'origin',
    'x-requested-with',
]


SSO_CLIENT_ID = os.getenv("SSO_CLIENT_ID")
SSO_REDIRECT_URL = os.getenv("SSO_REDIRECT_URL")
SSO_AUTH_URL=os.getenv("SSO_AUTH_URL")
SSO_TOKEN_URL=os.getenv("SSO_TOKEN_URL")
SSO_SECRET=os.getenv("SSO_SECRET")
SSO_USER_INFO_URL=os.getenv("SSO_USER_INFO_URL")

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "audit_format": {
            "format": "[%(asctime)s] %(levelname)s - %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "audit_log": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(os.path.dirname(__file__),"audit.log"),
            "maxBytes": 1024 * 1024 * 10,  # 10MB per file
            "backupCount": 10, 
            "formatter": "audit_format",
        },
    },
    "loggers": {
        "audit_logger": {
            "handlers": ["audit_log"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Mailchimp transactional API key (Mandrill)
MAILCHIMP_API_KEY = os.environ.get('MAILCHIMP_API_KEY', '')

# Base URL for the frontend (used in generating links)
BASE_URL = os.environ.get('BASE_URL', 'http://localhost:3000')

# File upload size limits
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB in bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB in bytes
