/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.futatsu.warmup2;

import org.junit.jupiter.api.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

class MainTest {
    @Test
    public void test1(){
        try {
            System.setIn(new FileInputStream("src/test/resources/1-in.txt"));
            ByteArrayOutputStream testOut = new ByteArrayOutputStream();
            PrintStream testPrintStream = new PrintStream(testOut);
            System.setOut(testPrintStream);
            Main.main(new String[0]);

            String actualOut = testOut.toString();
            Path filePath = Paths.get("src/test/resources/1-out.txt");
            List<String> lines = Files.readAllLines(filePath, StandardCharsets.UTF_8);

            String expectedOut = String.join("\n", lines);
            assertEquals(expectedOut.trim(), actualOut.trim());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    @Test
    public void test2(){
        try {
            System.setIn(new FileInputStream("src/test/resources/2-in.txt"));
            ByteArrayOutputStream testOut = new ByteArrayOutputStream();
            PrintStream testPrintStream = new PrintStream(testOut);
            System.setOut(testPrintStream);
            Main.main(new String[0]);

            String actualOut = testOut.toString();
            Path filePath = Paths.get("src/test/resources/2-out.txt");
            List<String> lines = Files.readAllLines(filePath, StandardCharsets.UTF_8);

            String expectedOut = String.join("\n", lines);
            assertEquals(expectedOut.trim(), actualOut.trim());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    @Test
    public void test3(){
        try {
            System.setIn(new FileInputStream("src/test/resources/3-in.txt"));
            ByteArrayOutputStream testOut = new ByteArrayOutputStream();
            PrintStream testPrintStream = new PrintStream(testOut);
            System.setOut(testPrintStream);
            Main.main(new String[0]);

            String actualOut = testOut.toString();
            Path filePath = Paths.get("src/test/resources/3-out.txt");
            List<String> lines = Files.readAllLines(filePath, StandardCharsets.UTF_8);

            String expectedOut = String.join("\n", lines);
            assertEquals(expectedOut.trim(), actualOut.trim());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    @Test
    public void test4() {
        try {
            System.setIn(new FileInputStream("src/test/resources/4-in.txt"));
            ByteArrayOutputStream testOut = new ByteArrayOutputStream();
            PrintStream testPrintStream = new PrintStream(testOut);
            System.setOut(testPrintStream);
            Main.main(new String[0]);

            String actualOut = testOut.toString();
            Path filePath = Paths.get("src/test/resources/4-out.txt");
            List<String> lines = Files.readAllLines(filePath, StandardCharsets.UTF_8);

            String expectedOut = String.join("\n", lines);
            assertEquals(expectedOut.trim(), actualOut.trim());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
