/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.futatsu.warmup2;

import java.util.*;

public abstract class APerson {
    private String name;
    private ArrayList<APerson> children;

    /**
     * Creates a person with a name and a list of children
     * @param name
     * @param children
     */
    public APerson(String name, ArrayList<APerson> children) {
        this.name = name;
        this.children = children;

    }

    /**
     * Returns the name of the Person
     * @return this.name
     */
    public String getName() {
        return this.name;
    }

    /**
     * Returns the children of the Person
     * @return this.children
     */
    public ArrayList<APerson> getChildren() {
        return this.children;
    }

    /**
     * To be implemented in the sub classes of Person. Should return whether they are a "mother" or a "father"
     * @return String -> "mother" or "father"
     */
    public abstract String toPathString();

    /**
     * Used for testing purposes to print a Person's children
     * @return String list of a Person's children
     */
    public String childrenToString(){
        String output = "";
        for (APerson child : children) {
            output += child.getName() + " ";
        }
        return output;
    }
}