name: Build Check
on:
 push:
   branches:
    - '*'         # Match all branches
    - '!main'     # Exclude main
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: Set up Node
     uses: actions/setup-node@v2
     with:
       node-version: '18'
   - name: Install and build
     working-directory: frontend
     run: |
       npm install
       npm run build
