/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package common;

import org.junit.jupiter.api.Test;
import static org.mockito.Mockito.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

import org.mockito.MockedStatic;
import utils.RandomUtil;

class CardTest {
    Card card;

    /**
     * Test case to mock random assignment in Card
     */
    @Test
    public void testCardGen1() {
        try (MockedStatic<RandomUtil> mockedStatic = mockStatic(RandomUtil.class)) {
            if(Constants.NUM_COLORS==Constants.STAR_ODDS){
                when(RandomUtil.getRandom(Constants.NUM_COLORS))
                        .thenReturn(0,1,2,3,4,0);

                card = new Card();
                // Verify calls for starGen and pebblesGen
                mockedStatic.verify(() -> RandomUtil.getRandom(Constants.NUM_COLORS), times(6));

            }
            else {
                // Mock the first call for starGen
                when(RandomUtil.getRandom(Constants.STAR_ODDS)).thenReturn(0);

                // Mock the subsequent calls for pebbleGen
                when(RandomUtil.getRandom(Constants.NUM_COLORS))
                        .thenReturn(0,1,2,3,4);  // First pebble is RED


                // Create a new Card instance, which will use the mocked RandomUtil
                card = new Card();

                // Verify that the first five calls were for pebbleGen with NUM_COLORS
                mockedStatic.verify(() -> RandomUtil.getRandom(Constants.NUM_COLORS), times(5));
                // Verify that the last call was for starGen with STAR_ODDS
                mockedStatic.verify(() -> RandomUtil.getRandom(Constants.STAR_ODDS), times(1));

            }

            // Validate that the card has a star
            assertTrue(card.getHasStar(), "The card should have a star");

            // Validate the generated pebbles sorted alphabetically
            ArrayList<Pebble> pebbles = card.getPebbles();
            assertEquals(5, pebbles.size(), "There should be exactly 5 pebbles");
            assertEquals(Pebble.BLUE, pebbles.get(0));
            assertEquals(Pebble.GREEN, pebbles.get(1));
            assertEquals(Pebble.RED, pebbles.get(2));
            assertEquals(Pebble.WHITE, pebbles.get(3));
            assertEquals(Pebble.YELLOW, pebbles.get(4));
        }
    }

    @Test
    public void testCardGen2() {

        try (MockedStatic<RandomUtil> mockedStatic = mockStatic(RandomUtil.class)) {
            if(Constants.NUM_COLORS==Constants.STAR_ODDS){
                when(RandomUtil.getRandom(Constants.NUM_COLORS))
                        .thenReturn(0,0, 0, 0, 0, 1);

                card = new Card();
                // Verify calls for starGen and pebblesGen
                mockedStatic.verify(() -> RandomUtil.getRandom(Constants.NUM_COLORS), times(6));

            }
            else {
                // Mock the subsequent calls for pebbleGen
                when(RandomUtil.getRandom(Constants.NUM_COLORS))
                        .thenReturn(0);

                // Mock the call for starGen
                when(RandomUtil.getRandom(Constants.STAR_ODDS)).thenReturn(1);

                // Create a new Card instance, which will use the mocked RandomUtil
                card = new Card();

                // Verify that the first five calls were for pebbleGen with NUM_COLORS
                mockedStatic.verify(() -> RandomUtil.getRandom(Constants.NUM_COLORS), times(5));
                // Verify that the last call was for starGen with STAR_ODDS
                mockedStatic.verify(() -> RandomUtil.getRandom(Constants.STAR_ODDS), times(1));


                // Validate that the card does not have a star
                assertTrue(!card.getHasStar(), "The card should not have a star");

                // Validate the generated pebbles
                ArrayList<Pebble> pebbles = card.getPebbles();
                assertEquals(5, pebbles.size(), "There should be exactly 5 pebbles");
                assertEquals(Pebble.RED, pebbles.get(0));
                assertEquals(Pebble.RED, pebbles.get(1));
                assertEquals(Pebble.RED, pebbles.get(2));
                assertEquals(Pebble.RED, pebbles.get(3));
                assertEquals(Pebble.RED, pebbles.get(4));
            }
        }
    }

    @Test
    public void testCanBuyCard() {

        try (MockedStatic<RandomUtil> mockedStatic = mockStatic(RandomUtil.class)) {
            if(Constants.NUM_COLORS==Constants.STAR_ODDS){
                when(RandomUtil.getRandom(Constants.NUM_COLORS))
                        .thenReturn(1,1,0,2,4,0);
            }
            else {
                when(RandomUtil.getRandom(Constants.NUM_COLORS))
                        .thenReturn(1, 1, 0, 2, 4);  // BLUE, BLUE, RED, GREEN, WHITE
                when(RandomUtil.getRandom(Constants.STAR_ODDS)).thenReturn(0);
            }
            card = new Card();

            ArrayList<Pebble> inventory1 = new ArrayList<>(Arrays.asList(Pebble.RED, Pebble.RED, Pebble.BLUE, Pebble.BLUE, Pebble.WHITE,Pebble.GREEN));
            ArrayList<Pebble> inventory2 = new ArrayList<>(Arrays.asList(Pebble.RED, Pebble.RED, Pebble.BLUE, Pebble.WHITE, Pebble.WHITE,Pebble.GREEN));

            assertTrue(card.canBuyCard(inventory1));
            assertTrue(!card.canBuyCard(inventory2));
        }
    }
}
